/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeThread */

#ifndef _Included_NativeThread
#define _Included_NativeThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeThread
 * Method:    fire
 * Signature: (LTestThread;)V
 */
JNIEXPORT void JNICALL Java_NativeThread_fire
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
